services:
  nginx:
    image: nginx:1.27.2
    ports:
      - "9085:9085"
    networks:
      - my_bridge
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  

networks:
  my_bridge:
    driver: bridge